absUser/urls.py
from django.urls import path
from . import views

from . import views as core_views


app_name = 'users'
urlpatterns = [
    path('api/users/', views.users_list, name="users-page"),
    path('login/', core_views.Login.as_view(), name='login'),
    path('signup/', core_views.signup, name='signup'),
    path('account/<int:user_id>/', views.user_page, name='userpage'),
    path('account/<int:user_id>/avatar', views.avatar_form, name='avatar_form'),
]

api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'projects', views.ProjectViewSet)
router.register(r'technologies', views.TechnologyViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

djangoapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

from absUser import urls as users_urls
from usersProjects import urls as project_urls
from api import urls as api_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('rest/api/', include(api_urls)),
    path('', include(project_urls)),
    path('', include(users_urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usersProjects/urls.py
from django.urls import path
from . import views


app_name = 'projects'
urlpatterns = [
    path('projects/<int:project_id>/', views.detail, name='detail'),
    path('projects/addproject/', views.add_project, name='add project'),
    path('projects/addtechnology', views.add_technology, name='add technology'),
    path('api/projects/', views.projects_list, name='projects list'),
    path('api/technologies/', views.technologies_list, name='technologies list'),
    path('projects/search/', views.projects_feed, name='projects_search'),
    path('projects/sort/', views.projects_feed, name='projects_sort'),
    path('home/', views.home, name='home'),
    path('projects/likes/', views.likes, name='likes'),
]

templates/projects/createProject.html
{% extends "base.html" %} 
{% block title %} New project {% endblock %} 
{% block content %}
<div class="card" style="width: 750px; margin:100px auto">
    <h5 class="card-header">New project</h5>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" style="width: 120px;">Title</span>
                </div>
                <input type="text" class="form-control" name="title">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" style="width: 120px;">Description</span>
                </div>
                <textarea type="text" class="form-control" name="description"></textarea>
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" style="width: 120px;">Users:</label>
                </div>
                <select size="3" multiple class="custom-select" name="users">
                    {% for user in users %}
                    <option value={{user.id}}> {{user}} </option>
                    {% endfor %}
                </select>
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" style="width: 120px;">Technologies:</label>
                </div>
                <select size="3" multiple class="custom-select" name="technologies">
                    {% for technology in techs %}
                    <option value={{technology.id}}> {{technology.title}} </option>
                    {% endfor %}
                </select>
            </div>
            <input type="submit" class="btn btn-primary" value="create">
        </form>
    </div>
</div>
{% endblock %}

templates/projects/detail.html
{% extends "base.html" %}
{% block title %} {{ project }} {% endblock %}
{% block content %}
<div class="card" style="width: 750px; margin:100px auto">
    <h5 class="card-header">{{ project }}</h5>
    <div class="card-body">
        <p class="card-text">Description: {{ project.description }}</p>
        <p class="card-text">Users:</p>
        <ul>
            {% for user in project.users.all %}
                <li> <a href="{% url 'users:userpage' user.id %}">{{ user }}</a></li>
            {% endfor %}
        </ul>
        <p class="card-text">Technologies: {{ technologies }}</p>
    </div>
</div>
{% endblock %}

templates/projects/paginator.html
    <ul id="pagination" class="pagination" style="margin: 10px">
        {% if projects.has_previous %}<li class="page-item">
            <span class="page-link" pageNumber="{{ projects.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </span>
        </li>
        <li class="page-item">
            <span class="page-link" pageNumber="{{ projects.previous_page_number }}">{{ projects.previous_page_number }}</span>
        </li>{% else %}
        <li class="page-item disabled">
            <span class="page-link" pageNumber="1" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </span>
        </li>{% endif %} 
        <li class="page-item disabled">
            <span id="numberPage" class="page-link" pageNumber="{{ projects.number }}">{{ projects.number }}</span>
        </li>
        {% if projects.has_next %}<li class="page-item">
            <span class="page-link" pageNumber="{{ projects.next_page_number }}">{{ projects.next_page_number }}</span>
        </li>
        <li>
            <span class="page-link" pageNumber="{{ projects.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </span>
        </li>{% else %}
        <li class="page-item disabled">
            <span class="page-link" pageNumber="{{ projects.paginator.num_pages }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </span>
        </li>
        {% endif %}
    </ul>

templates/projects/projects.html
{% extends "base.html" %} 
{% block title %} Projects {% endblock %} 
{% block external_scripts %}
<script>
    $(document).ready(function () {
        function trimStr(s) {
            s = s.replace(/^\s+/gi, '');
            s = s.replace(/\s+$/gi, '');
            return s;
        };
        var textToFind = ''
        var numPage = ''

        $('#search').click(function () {
            textToFind = trimStr($('input').val());
            $.ajax({
                type: "GET",
                data: { "text": textToFind },
                url: "/projects/search/",
                success: function (data) {
                    $('#list-projects').html(data.projects_body);
                    $('#paginator').html(data.pagination);
                }
            });
        });

        $(document).on('click','.like', function(){
            numPage = $('#numberPage').text();
            var like = +$(this).children('.number-of-likes').text();
            $.ajax({
                type: "POST",
                data: { 
                    "numPage": numPage, 
                    "like": like, 
                    "projectId": $(this).attr('id'), 
                    "csrfmiddlewaretoken": $("[name=csrfmiddlewaretoken]").val(),
                },
                url: "/projects/likes/",
                success: function (data) {
                    $('#list-projects').html(data.projects_body);
                    $('#paginator').html(data.pagination);
                },
            });
        });

        $(document).on('click', '.page-link', function(){
            numberPage = $('#numberPage').text();
            numPage = $(this).attr("pageNumber");
            $.ajax({
                type: "GET",
                data: { "text": textToFind, "numPage": numPage },
                url: '/projects/sort/', 
                success: function (data) {
                    $('#list-projects').html(data.projects_body);
                    $('#paginator').html(data.pagination);
                }               
            });
        });
    });
</script> 
{% endblock %} 
{% block content %}
<div class="card" style="width: 750px; margin:100px auto">
    <nav class="navbar navbar-light bg-light form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" name="find" value="">
        <button id="search" class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
    </nav>
    <div id="list-projects">
        {% include "projects/projects_feed.html" %}
    </div>
    <nav id="paginator" aria-label="Page navigation example">
    {% include "projects/paginator.html" %}
    </nav>
</div>
{% endblock %}

templates/projects/projects_feed.html
{% for project in projects %}
<div class="card" style="margin: 20px">
    <div class="card-header"> <a href="{% url 'projects:detail' project.id %}">{{ project }}</a></div>
    <div class="card-body">
        <p class="card-text">{{ project.description }}</p>
        <p>
            <b>Technologies:</b> {% for tech in project.technologies.all %} {{ tech }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p>
            <b>Users:</b> {% for us in project.users.all %} {{ us }}{% if not forloop.last %}, {% endif %} {% endfor %}
        </p>
        {% csrf_token %}
        {% if project.projects_id.all.count %}
        <button type="button" class="like btn btn-default likes-button" id="{{ project.id }}">
            &#x1f5a4;
            <span class="number-of-likes">{{ project.projects_id.all.count }}</span>
        </button>
        {% else %}
        <button type="button" class="like btn btn-default likes-button" id="{{ project.id }}">
            &#x1f5a4;
            <span class="number-of-likes"></span>
        </button>
        {% endif %}
    </div>
</div>
{% endfor %}

templates/projects/projectslist.html
{% extends "base.html" %} 
{% block title %} Projects {% endblock %} 
{% block content %}
<div class="card" style="background-color: white; border: 1px">
<pre>{
    'error': false, 
    'Projects':[ {% for i in projects %}
        { 
            title: {{ i.title }},
            description: {{ i.description }},
            Users:[{% for n in i.users.all %}
                { 
                    id: {{ n.id }}
                    name: {{ n }}
                    first name: {{ n.first_name }}
                    last name: {{ n.last_name }}
                    age: {{ n.age }}
                },{% endfor %}
            ]
        },{% endfor %}
    ]
}</pre> 
</div>
{% endblock %}