absUser/urls.py
from django.urls import path
from . import views

from . import views as core_views


app_name = 'users'
urlpatterns = [
    path('api/users/', views.users_list, name="users-page"),
    path('login/', core_views.Login.as_view(), name='login'),
    path('signup/', core_views.signup, name='signup'),
    path('account/<int:user_id>/', views.user_page, name='userpage'),
    path('account/<int:user_id>/avatar', views.avatar_form, name='avatar_form'),
]

api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'projects', views.ProjectViewSet)
router.register(r'technologies', views.TechnologyViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

djangoapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

from absUser import urls as users_urls
from usersProjects import urls as project_urls
from api import urls as api_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('rest/api/', include(api_urls)),
    path('', include(project_urls)),
    path('', include(users_urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usersProjects/urls.py
from django.urls import path
from . import views


app_name = 'projects'
urlpatterns = [
    path('projects/<int:project_id>/', views.detail, name='detail'),
    path('projects/addproject/', views.add_project, name='add project'),
    path('projects/addtechnology', views.add_technology, name='add technology'),
    path('api/projects/', views.projects_list, name='projects list'),
    path('api/technologies/', views.technologies_list, name='technologies list'),
    path('projects/search/', views.projects_feed, name='projects_search'),
    path('projects/sort/', views.projects_feed, name='projects_sort'),
    path('home/', views.home, name='home'),
    path('projects/likes/', views.likes, name='likes'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <script src="https://code.jquery.com/jquery-1.10.1.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    {% block external_scripts %}{% endblock %}
</head>

<body style="background-color: whitesmoke">
    {% if user.is_authenticated %}
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap shadow">
        <div class="container nav-item text-nowrap">
            <div class="navbar-header">
                <a href="{% url 'projects:home' %}" class="navbar-brand" style="color: lightgray">Home</a>
                <a href="{% url 'users:users-page' %}" class="navbar-brand" style="color: lightgray">Users</a>
                <a href="{% url 'projects:projects list' %}" class="navbar-brand" style="color: lightgray">Projects</a>
                <a href="{% url 'projects:technologies list' %}" class="navbar-brand" style="color: lightgray">Technologies</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li id="drop" class="dropdown">
                    <a id="account" class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                        Account
                    </a>
                    <div class="dropdown-menu" style="position: absolute; transform: translate3d(0px, 38px, 0px); top: 0px; left: 0px; will-change: transform;">
                        <a class="dropdown-item" href="{% url 'users:userpage' user.id %}">{{user}}</a>
                        <a class="dropdown-item" href="{% url 'projects:add project' %}">Create project</a>
                        <a class="dropdown-item" href="{% url 'projects:add technology' %}">Create technology</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    {% endif %}
    <div class="container" style="margin:100px auto">
        {% block content %}{% endblock %} 
    </div>
    <script>
        $(document).ready(function () {
            $('#account').click(function () {
                $('#drop').toggleClass('show');
                $('.dropdown-menu').toggleClass('show');
            })
        })
    </script>
    <!-- <script src="../static/js.js"></script> -->
    <!-- <script src="js.js"></script> -->
</body>

</html>